version: "3.7"
services:
  site:
    image: node:18.9
    container_name: site
    working_dir: /usr/src/site
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./site:/usr/src/site
    # command: >
    #   bash -c "npm install && npm install nodemon -g && nodemon src/server.js"
