version: "3.7"
services:
  site:
    image: node:16.17
    container_name: site
    working_dir: /usr/src/site
    tty: true
    ports:
      - '5173:5173'
    volumes:
      - ./site:/usr/src/site
    command: >
      bash -c "npm i -g pnpm && pnpm i && pnpm dev"
